### ISSUE TITLE
Union behaves as intersection

### ISSUE THREAD

**Issue by MSE1188** [Meerownymous/Tonga#4]
Edit: See last comment. 

### Expected Behavior
See https://github.com/icarus-consulting/Yaapii.Atoms/pull/568 for fix of this issue

### Actual Behavior
The union only works with distinct enumerables. On non-distinct enumerables the result is not as expected.
E.g. ```Union.New(ManyOf.New(1,1,2), ManyOf.New(2,3))``` results in an enumerable ```[1,2]```, even if ```[2]``` would be expected.
The other way around  ```Union.New(ManyOf.New(2,3), ManyOf.New(1,1,2))``` works fine.

### The log given by the failure.

**Comment by Meerownymous** [comment]
Thanks for bringing this one up.

**Comment by Meerownymous** [comment]
fixed

**Comment by Meerownymous** [comment]
@MSE1188 There seems to be some confusion with the terminology. The union of [1, 1, 2] and [2, 3] would be [1, 2, 3].
While the *intersection* of [1, 1, 2] and [2, 3] would be [2].
